; PlatformIO Project Configuration File for ESP32-C3 Wearable Acquisition Node
; Thesis: An Internet of Things-Based Framework for Cardiac Arrhythmia Detection
; Authors: Bauzon, Condino, Delos Angeles, Rana, Villaflor (3CPE-2A, Univ. of the East)

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D I2C_SDA_PIN=8
    -D I2C_SCL_PIN=9

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
